name: Semantic Release for Apps

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0

      # Get the folder paths of changed files
      - name: Get changed directories
        id: changed_dirs
        run: |
          CHANGED_DIRS=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | awk -F/ 'BEGIN{OFS=FS} NF--')
          if [[ -z $CHANGED_DIRS ]]; then
            echo "::set-output name=dirs::"
          else
            echo "::set-output name=dirs::$CHANGED_DIRS"
          fi

      # Iterate over the changed directories
      - name: Iterate over changed directories
        id: iterate_dirs
        run: |
          for dir in ${{ steps.changed_dirs.outputs.dirs }}
          do
            echo "::set-output name=dir::$dir"
          done

      # Update the tag format to include the names of the directories
      - name: Update tag format
        id: update_tag_format
        run: |
          APP_DIRS="${{ steps.iterate_dirs.outputs.dir }}"
          if [[ -z $APP_DIRS ]]; then
            echo "::set-output name=tag_format::v\${version}"
          else
            APP_NAMES=""
            IFS=$'\n' read -r -d '' -a dirs_array <<< "$APP_DIRS"
            for dir in "${dirs_array[@]}"
            do
              APP_NAMES+=$(echo "$dir" | awk '{print tolower($0)}')"-"
            done
            APP_NAMES=${APP_NAMES::-1}
            echo "::set-output name=tag_format::${APP_NAMES}-v\${version}"
          fi

      # Determine the paths to the CHANGELOG.md files for each directory
      - name: Determine CHANGELOG.md paths
        id: changelog_paths
        run: |
          APP_DIRS="${{ steps.iterate_dirs.outputs.dir }}"
          if [[ -z $APP_DIRS ]]; then
            echo "::set-output name=paths::./CHANGELOG.md"
          else
            CHANGELOG_PATHS=""
            IFS=$'\n' read -r -d '' -a dirs_array <<< "$APP_DIRS"
            for dir in "${dirs_array[@]}"
            do
              if [[ -f "$dir/CHANGELOG.md" ]]; then
                CHANGELOG_PATHS+="$dir/CHANGELOG.md"$'\n'
              fi
            done
            if [[ -z $CHANGELOG_PATHS ]]; then
              echo "::set-output name=paths::"
            else
              echo "::set-output name=paths::$CHANGELOG_PATHS"
            fi
          fi

      # Run semantic release for each directory
      - name: Semantic Release
        id: semantic
        run: |
          APP_DIRS="${{ steps.iterate_dirs.outputs.dir }}"
          CHANGELOG_PATHS="${{ steps.changelog_paths.outputs.paths }}"
          IFS=$'\n' read -r -d '' -a dirs_array <<< "$APP_DIRS"
          IFS=$'\n' read -r -d '' -a paths_array <<< "$CHANGELOG_PATHS"
          for i in "${!dirs_array[@]}"
          do
            dir=${dirs_array[i]}
            changelog_path=${paths_array[i]}
            echo "Running semantic release for $dir"
            echo "Changelog path: $changelog_path"
            echo "Tag format: $dir-v\${version}"
            # Run semantic release for each directory using the appropriate tag format and changelog path
            docker run -e GITHUB_TOKEN="${{ secrets.PAT_GITHUB2 }}" \
              -e INPUT_TAG_FORMAT="$dir-v\${version}" \
              -e INPUT_ADDITIONAL_PACKAGES="['@semantic-release/changelog', '@semantic-release/git']" \
              -e INPUT_PLUGINS="['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', ['@semantic-release/changelog', { \"changelogFile\": \"$changelog_path\" }], '@semantic-release/github', ['@semantic-release/git', { \"assets\": [\"$changelog_path\"] }]]" \
              -e INPUT_BRANCHES="['master']" \
              -v "$(pwd):/github/workspace" \
              ghcr.io/codfish/semantic-release-action:v2
          done

      - name: Semantic Release Output Summary
        id: semantic_summary
        run: |
          echo "### Semantic Version = ${{ steps.semantic.outputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ toJson(steps.semantic.outputs) }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true


        
# name: Semantic Release for Apps

# on:
#   push:
#     branches:
#       - master
#     paths:
#     - 'modules/**'
# permissions: write-all

# jobs:
#   release:
#     name: Semantic Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         id: checkout
#         with:
#           fetch-depth: 0

#       # Get the name of the directory that was changed
#       - name: Get changed directories
#         id: changed_dirs
#         run: |
#           echo "::set-output name=dirs::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | awk -F/ '{print $0}' | sort -u)"

#       # Check if there are any tags available
#       - name: Check for tags
#         id: check_tags
#         run: |
#           if [[ -z $(git tag -l) ]]; then
#             echo "::set-output name=has_tags::false"
#           else
#             echo "::set-output name=has_tags::true"
#           fi

#       # Update the tag format to include the name of the directory
#       - name: Update tag format
#         id: update_tag_format
#         run: |
#           APP_NAME=$(echo "${{ steps.changed_dirs.outputs.dirs }}" | awk '{print tolower($0)}')
#           echo "::set-output name=tag_format::${APP_NAME}-v\${version}"

#         # Add new version to changelog or set initial version if no tags are available
#       - name: Add new version to changelog
#         id: add_version_to_changelog
#         run: |
#             if [[ "${{ steps.check_tags.outputs.has_tags }}" == "true" ]]; then
#             version=$(git describe --tags --abbrev=0)
#             else
#             version="1.0.0"
#             echo "## Changelog" > CHANGELOG.md
#             fi
#             sed -i "s|\[[0-9]\+\.[0-9]\+\.[0-9]\+\]|[${version}] $(date +'%Y-%m-%d')|" CHANGELOG.md
            
#       # https://github.com/marketplace/actions/semantic-release-action#usage
#       - name: Semantic Release
#         uses: docker://ghcr.io/codfish/semantic-release-action:v2
#         id: semantic
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2 }}
#         with:
#           tag_format: '${{ steps.update_tag_format.outputs.tag_format }}'
#           additional_packages: |
#             ['@semantic-release/changelog', '@semantic-release/git']
#           plugins: |
#             ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', ['@semantic-release/changelog', {changelogTitle: '# CHANGELOG', "changelogFile": "modules/aws/eks/eks-simple/modules/CHANGELOG.md"}], '@semantic-release/github', ['@semantic-release/git', {
#               "assets": ["modules/aws/eks/eks-simple/modules/CHANGELOG.md"]
#             }]]
#           # specify default branches to add support for the `main` branch
#           # which semantic-release doesn't have as a default yet.
#           branches: |
#             [
#               'master'
#             ]
#       # Get the latest version tag
#       - name: Get latest version tag
#         run: |
#           version=$(git describe --tags --abbrev=0)
#           echo "::set-output name=version::$version"

#       - name: Semantic Release Output Summary
#         id: semantic_summary
#         run: |
#           echo "### Semantic Version = ${{ steps.semantic.outputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
#           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
#           echo "${{ toJson(steps.semantic.outputs) }}" >> $GITHUB_STEP_SUMMARY
#           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
#         continue-on-error: true