name: Semantic Release for Apps

on:
  push:
    branches:
      - master
    paths:
      - 'modules/**'

permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0

      - name: Get changed directory
        id: get_changed_directory
        run: |
          CHANGED_DIRECTORY=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | awk -F/ 'NR==1{print $1}')
          echo "::set-output name=changed_directory::$CHANGED_DIRECTORY"

      - name: Get changelog file
        id: get_changelog_file
        run: |
          CHANGED_DIRECTORY=${{ steps.get_changed_directory.outputs.changed_directory }}
          CHANGELOG_FILE="modules/${CHANGED_DIRECTORY}/changelog.md"
          echo "::set-output name=changelog_file::$CHANGELOG_FILE"

      - name: Update changelog
        id: update_changelog
        run: |
          CHANGELOG_FILE=${{ steps.get_changelog_file.outputs.changelog_file }}
          if [[ -f "$CHANGELOG_FILE" ]]; then
            echo "## Changelog" > $CHANGELOG_FILE
            # Add any custom logic here to update the changelog file for the changed directory
          fi

      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2 }}
          CHANGELOG_FILE: ${{ steps.get_changelog_file.outputs.changelog_file }}
        with:
          # ... other configuration options ...
          tag_format: 'v${version}'
          additional_packages: |
            ['@semantic-release/changelog', '@semantic-release/git']
          plugins: |
            - '@semantic-release/commit-analyzer'
            - '@semantic-release/release-notes-generator'
            - - '@semantic-release/changelog'
                - changelogFile: ${{ steps.get_changelog_file.outputs.changelog_file }}
            - '@semantic-release/github'
            - '@semantic-release/git'
          branches: |
            [
              'master'
            ]
