name: Semantic Release for Apps

on:
  push:
    branches:
      - master
    paths:
    - 'modules/**'
permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0

      # Get the name of the directory that was changed
      - name: Get changed directories
        id: changed_dirs
        run: |
          echo "::set-output name=dirs::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | awk -F/ '{print $0}' | sort -u)"

      - name: Run semantic-release.sh
        id: semantic_release_script
        run: |
            chmod +x semantic-release.sh
            source ./semantic-release.sh
  
      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: semantic
        env:
            GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2 }}
        with:
            tag_format: '${{ steps.semantic_release_script.outputs.tag_format }}'
            additional_packages: |
                ['@semantic-release/changelog', '@semantic-release/git']
            plugins: |
                ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', ['@semantic-release/changelog', {changelogTitle: '# CHANGELOG'}], '@semantic-release/github', '@semantic-release/git']
            branches: |
                [
                'master'
                ]
        
      # Get the latest version tag
      - name: Get latest version tag
        run: |
          version=$(git describe --tags --abbrev=0)
          echo "::set-output name=version::$version"

      - name: Semantic Release Output Summary
        id: semantic_summary
        run: |
          echo "### Semantic Version = ${{ steps.semantic.outputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ toJson(steps.semantic.outputs) }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true